[package]
name = "chess-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
chess = { git = "https://github.com/sklbz/chess-board-representation", branch = "master" }
multilayer-perceptron = { git = "https://github.com/sklbz/multilayer-perceptron", branch = "master" }
